'use strict';
const { byggDemo } = require('./_veg3d_felles.js');
(async () => {
  const t0 = Date.now();
  const d = await byggDemo();
  const r = d.res;
  console.log('lengde', r.lengdeKart.toFixed(2), 'profiler', r.profiler.length, 'dS', (r.profiler[1].s - r.profiler[0].s).toFixed(3));
  console.log('bakkefaktor', d.bf);
  console.log('sum skjaering', r.sum.skjaering.toFixed(2), 'fylling', r.sum.fylling.toFixed(2));
  console.log('har geometri paa profil 0?', !!r.profiler[0].geometri, ' sider?', !!r.profiler[0].sider);
  const p = r.profiler[20];
  console.log('profil 20 nøkler:', Object.keys(p).join(','));
  console.log('  s', p.s, 'hb', p.halvbredde, 'fotV', p.fotVenstre.toFixed(3), 'fotH', p.fotHoyre.toFixed(3));
  console.log('  zFotV', p.zFotVenstre.toFixed(3), 'zFotH', p.zFotHoyre.toFixed(3), 'vegnivaa', p.vegnivaa.toFixed(3));
  console.log('  sider[-1] type', p.sider[-1].type, 'knekk', p.sider[-1].knekk.length, 'truffet', p.sider[-1].truffet);
  console.log('  sider[1] type', p.sider[1].type, 'knekk', p.sider[1].knekk.length);
  console.log('  geometri.jord lengde', p.geometri.jord.length, 'terreng', p.geometri.terreng.length);
  console.log('  jord[0..3]', JSON.stringify(p.geometri.jord.slice(0,3)));
  console.log('tid', Date.now()-t0, 'ms');
})();
